Develop
emotional-help-competition/backend pull request #84
Opened 2022-12-08 11:44 UTC by kolesroma

2022-12-08 16:38 UTC, maximelyashevich requested changes
Reviewed from my side - two new PR should be created:
1. Refactor unit testing - @HakobTono please pick up this task
2. Refactor calculating service - @GeloPakDev please pick up this task

Regards,
Maks

2022-12-08 16:38 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/controller/QuizController.java
> +import com.epam.emotionalhelp.service.QuizResultService;
Why do we need this import?

2022-12-08 16:38 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/controller/QuizController.java
> +import com.epam.emotionalhelp.controller.config.CORSConfig;
Why do we need this import?

2022-12-08 16:38 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/controller/QuizResultController.java
> +import com.epam.emotionalhelp.controller.config.CORSConfig;
Why do we need this import?

2022-12-08 16:38 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/controller/QuizResultController.java
>  public class QuizResultController {
Please restore validation and Open-API documentation for this controller.

2022-12-08 16:38 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/controller/dto/EmotionDto.java
> +import lombok.*;
Please replace with single import statements.

2022-12-08 16:38 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/model/RecommendationEntity.java
> +import javax.persistence.*;
Please replace with single import statements.

2022-12-08 16:38 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/service/impl/EmotionServiceImpl.java
> +    @Autowired
No nee to use autowired here since we use  RequiredArgsConstructor annotation - it creates only one constructor for a class field

2022-12-10 11:38 UTC, kolesroma commented on src/main/java/com/epam/emotionalhelp/service/impl/QuizResultServiceImpl.java
> +        quizAttempt.setCreateDate(LocalDateTime.now());
Consider builder

2022-12-10 11:48 UTC, kolesroma commented on src/main/java/com/epam/emotionalhelp/service/impl/QuizResultServiceImpl.java
> +            emotions = new ArrayList<>(inputEmotions.subList(0, LIST_SLICE_SIZE));
Simplify to
 ArrayList<>(inputEmotions.subList(0, LIST_SLICE_SIZE));
If list size is 6 you slice anyway 0 to 6

2022-12-10 19:29 UTC, maximelyashevich commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-collections4 -->
```suggestion
```

2022-12-10 22:15 UTC, maximelyashevich reviewed
Please review my comments and provide code refactoring.

Regards,
Maks

2022-12-10 22:26 UTC, kolesroma commented on src/main/java/com/epam/emotionalhelp/service/impl/EmotionServiceImpl.java
> +
@maximelyashevich is it a good idea to make static method returns supplier in ResourceNotFoundException class?

2022-12-10 23:02 UTC, maximelyashevich reviewed
Hi @kolesroma,
Please review your javadoc and make it more readable :)

Regards,
Maks

2022-12-10 23:02 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/controller/EmotionController.java
> +     */
```suggestion
    /**
     * Find all emotions.
     *
     * @param pageable pageable
     * @return emotions
     */
```

2022-12-10 23:02 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/controller/EmotionController.java
> +     */
```suggestion
    /**
     * Find by an emotion by id.
     *
     * @param id the id
     * @return the emotion response dto
     */
```

2022-12-10 23:02 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/controller/EmotionController.java
> +     */
```suggestion
    /**
     * Update an emotion by id.
     *
     * @param id                the id
     * @param emotionRequestDto the emotion request dto
     * @return the emotion response dto
     */
```

2022-12-11 17:55 UTC, maximelyashevich reviewed
Hi @GeloPakDev,
Please review my recommendations and provide some code refactoring.

2022-12-11 17:55 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/exception/ResourceNotFoundException.java
> +        UNKNOWN_ENTITY_NOT_FOUND
```suggestion
        EMOTION_NOT_FOUND
```

2022-12-11 17:55 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/service/impl/QuizResultServiceImpl.java
> +    private static final int MAX_SCORE_VALUE = 5;
```suggestion
public class QuizResultServiceImpl implements QuizResultService {

    private static final int MAX_SCORE_VALUE = 5;
```

2022-12-11 17:55 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/service/impl/QuizResultServiceImpl.java
> +    private final QuizResultRepository quizResultRepository;
```suggestion
    private static final int LIST_SLICE_SIZE = 6;
    
    private final QuizResultRepository quizResultRepository;
```

2022-12-11 17:55 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/service/impl/QuizResultServiceImpl.java
> +        return new AttemptDto(quizAttempt.getId());
```suggestion
        // 1. Find passed Quiz
        var quiz = quizRepository.findById(quizId);
        
        // 2. Create QuizAttempt object
        var quizAttempt = QuizAttempt.builder().createDate(LocalDateTime.now()).build();
        var quizAttemptFinal = quizAttemptRepository.save(quizAttempt);
        
        // 3. Filter the list to divide data by Emotions
        var emotionsMap = filterByEmotions(emotions);
        var emotionPercentages = calculateEmotionPercentage(emotionsMap);
        
        // 4. Get the set of emotions
        emotionPercentages.forEach((emotion, score) -> {
            var quizResult = QuizResult.builder()
                    .attempt(quizAttemptFinal)
                    .emotion(emotion)
                    .score(score)
                    .build();
            quiz.ifPresent(quizResult::setQuiz);
            quizResultRepository.save(quizResult);
        });
        return new AttemptDto(quizAttempt.getId());
```

2022-12-11 17:55 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/service/impl/QuizResultServiceImpl.java
> +        return resultList;
```suggestion
        var resultList = new ArrayList<EmotionalMapDto>();
        
        // 1. Find QuizResult(Emotion, Overall score)
        var quizResults = quizResultRepository.findAllByAttemptId(attemptId);
        
        // 2. Extract emotion and get subcategories based on '%'
        quizResults.forEach(quizResult -> {
            var quizResultEmotionDto = new EmotionalMapDto();
            var emotion = quizResult.getEmotion();
            quizResultEmotionDto.setCategory(emotion.getDescription());
            
            // find all subcategories
            // if score is equal to 0 it means that list with subcategories should be empty
            if (quizResult.getScore() == 0) {
                quizResultEmotionDto.setSubCategories(new ArrayList<>());
            } else {
                var categoryList = initSubcategoryList(quizResult, emotion.getId());
                quizResultEmotionDto.setSubCategories(categoryList);
            }
            resultList.add(quizResultEmotionDto);
        });
        return resultList;
```

2022-12-11 17:55 UTC, maximelyashevich commented on src/main/java/com/epam/emotionalhelp/service/impl/QuizResultServiceImpl.java
> +        IntStream.range(0, maxSize).mapToObj(i -> result).forEach(QuizResultUtil::fillMapByEmptyEmotions);
```suggestion

        // 1. Fill map with EMOTIONS and its SUBCATEGORIES
        final Map<EmotionCategory, List<EmotionDto>> result = new HashMap<>();
        
        // 2. Limit input emotions by 6 maximum
        var emotions = new ArrayList<>(inputEmotions.subList(0, LIST_SLICE_SIZE));
        emotions.forEach(emotionDto -> {
            // find emotion and extract description
            var emotion = emotionRepository.findById(emotionDto.getEmotionId()).orElse(new Emotion());
            var description = emotion.getDescription().toUpperCase();
            
            // check if map already contains EMOTION
            var category = EmotionCategory.valueOf(description);
            if (result.containsKey(category)) {
                result.get(category).add(emotionDto);
            } else {
                var data = new ArrayList<EmotionDto>();
                data.add(emotionDto);
                result.put(category, data);
            }
        });
        
        // 3. Fill map with EMOTIONS which are not included in the input list
        final int maxSize = LIST_SLICE_SIZE - result.values().size();
        IntStream.range(0, maxSize).mapToObj(i -> result).forEach(QuizResultUtil::fillMapByEmptyEmotions);
```

2022-12-12 20:45 UTC, merged